version: '3.7'

services:
  k6:
    image: loadimpact/k6:latest
    hostname: k6
    container_name: stress_k6
    networks:
      - centrifugal
    ports:
      - "6565:6565"
    volumes:
      - ./tests:/scripts

networks:
  centrifugal: