version: '3.7'

services:
  tests:
    image: golang:1.17-alpine
    container_name: tests
    volumes:
      - ./tests:/tests:delegated
    env_file:
      - .env
    tty: true
    depends_on:
      - centrifugo
      - prometheus
      - grafana
      - cadvisor
    working_dir: /tests

  centrifugo:
    image: centrifugo/centrifugo:latest
    container_name: centrifugo
    volumes:
      - ./config/centrifugo.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8000:8000
#    ulimits:
#      nofile:
#        soft: 65535
#        hard: 65535
#    deploy:
#      resources:
#        limits:
#          cpus: '2'

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run/:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./config/grafana/datasource_prometheus.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
