version: '3.7'

services:
  k6:
    image: loadimpact/k6:latest
    hostname: k6
    container_name: stress_k6
    ports:
      - "6565:6565"
    depends_on:
      - centrifugo
      - telegraf
    volumes:
      - ./tests:/scripts

  telegraf:
    image: telegraf:1.18.2-alpine
    ports:
      - 8186:8186
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:latest
    volumes:
      - ./config/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8000:8000
  #    ulimits:
  #      nofile:
  #        soft: 65535
  #        hard: 65535