{
 "title": "Centrifugo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Clients connected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "centrifugo_node_num_clients" }
   ]
  },
  {
   "title": "Publication messages received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "centrifugo_node_messages_received_count{type=\"publication\"}"
    }
   ]
  },
  {
   "title": "Publication message latency ??? (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(centrifugo_client_command_duration_seconds_sum{method=\"publish\"}[1m])"
    }
   ]
  }
 ]
}