global:
  scrape_interval: 5s

scrape_configs:
  - job_name: centrifugo
    scrape_interval: 5s
    static_configs:
      - targets:
          - centrifugo:8000
  - job_name: cadvisor
    scrape_interval: 2s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: custom
    scrape_interval: 2s
    static_configs:
      - targets:
          - host.docker.internal:8082
